name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"
  PYTHONDEVMODE: "1"  # -X dev
  PYTHONWARNDEFAULTENCODING: "1"  # -X warn_default_encoding

jobs:
  latex:
    runs-on: ubuntu-latest
    name: LaTeX
    container:
      image: ghcr.io/sphinx-doc/sphinx-ci

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3"
    - name: Check Python version
      run: python --version --version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[test]
    - name: Test with pytest
      run: python -m pytest -vv --durations 25
      env:
        PYTHONWARNINGS: "error"  # treat all warnings as errors
        DO_EPUBCHECK: "1"
