name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"
  PYTHONDEVMODE: "1"  # -X dev
  PYTHONWARNDEFAULTENCODING: "1"  # -X warn_default_encoding

jobs:
  latex:
    runs-on: ubuntu-latest
    name: LaTeX

    steps:
    - name: Install epubcheck
      run: |
        mkdir /tmp/epubcheck && cd /tmp/epubcheck
        wget -q https://github.com/w3c/epubcheck/releases/download/v5.1.0/epubcheck-5.1.0.zip
        unzip -q epubcheck-5.1.0.zip
        cp -a epubcheck-5.1.0/ /usr/share/java/

    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3"
    - name: Check Python version
      run: python --version --version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
    - run: mkdir -p t ./tmp/root
    - run: cp -a tests/roots/test-root/* ./tmp/root
    - run: python -m sphinx build -M epub ./tmp/root/ ./tmp/root/_build/
    - name: Run epubcheck
      run: java -jar /usr/share/java/epubcheck-5.1.0/epubcheck.jar ./tmp/root/_build/epub/SphinxTests.epub
    - uses: actions/upload-artifact@v4
      with:
        name: epub
        path: ./tmp/root/_build/epub/SphinxTests.epub
